# Generated by Django 2.0.1 on 2018-01-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LogContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('valid', models.BooleanField(default=False)),
                ('parse_details', models.TextField()),
                ('parsed', models.TextField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_parser_app.Bug')),
                ('log_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_parser_app.LogContentType')),
            ],
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='logitem',
            name='log_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_parser_app.LogType'),
        ),
    ]
