# Generated by Django 2.0.1 on 2018-01-27 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('log_parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('project', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='log_parser_app.Project'),
        ),
    ]
